version: 2
jobs:
  build:
    docker:
      - image: codecentric/springboot-maven3-centos

    working_directory: ~/codeclimate
    steps:
      - checkout
      - run:
          name: setup code climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
            ./cc-test-reporter before-build
          when: always

      - run:
          name: code-coverage
          command: |
            mvn test
      - run:
          name: set jacoco.xml path for code climate
          command: |
            JACOCO_SOURCE_PATH=src/main/java ./cc-test-reporter \
            format-coverage target/jacoco/jacoco.xml     \
            --input-type jacoco

      - run:
          name: upload code climate report
          command: ./cc-test-reporter upload-coverage -r $CC_TEST_REPORTER_ID
          when: on_success

